name: mi_ipred_plantel_exterior
description: A Flutter web + Android compatible app for IPRED with WebSocket real-time updates
version: 1.0.0+83

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.0.0
  universal_html: ^2.0.8
  barcode: ^2.2.0
  web_socket_channel: ^3.0.3
  synchronized: ^3.3.1
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  web: ^1.1.1
  path: ^1.9.1
  path_provider: ^2.1.5
  decimal: ^3.2.4
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  advanced_datatable: ^0.0.9
  equatable: ^2.0.7
  collection: ^1.19.1
  crypto: ^3.0.6
  circular_countdown_timer: ^0.2.4
  material_design_icons_flutter: ^7.0.7296
  js: ^0.6.7
  xml: ^6.5.0
  drift: 2.31.0
  sqlite3_flutter_libs: 0.5.26
  
dev_dependencies:
  flutter_lints: ^5.0.0
  drift_dev: ^2.31.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"